<?php
/**
 *
 * Copyright (c) 2019. Jamersan, LLC
 * Author: William French
 * https://www.jamersan.com | william.french@jamersan.com
 *
 */
?>
<?php /** @var $block \Jamersan\GoogleTagManager\Block\GtmCode **/ ?>

<!-- Google Tag Manager by Jamersan -->
<noscript><iframe src="<?= '/' . '/' ?>www.googletagmanager.com/ns.html?id=<?php echo $block->getAccountId() ?>"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager by Jamersan -->
